---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum: 
        name: python-pip
        state: present
    - name: Install docker-py pthon module
      pip:
        name: docker-py
        state: present
      vars:
        ansible_python_interpreter: /bin/python3
    - name: Start docker container
      docker_container:
        name: vidurinda
        image: "vidurinda/ices:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
