---
- hosts: dev
  become: True
  tasks:
    - name: Start docker container
      docker_container:
        name: vidurinda
        image: "vidurinda/ices:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
